### ISSUE TITLE
Grading jobs finish without reporting results

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieGrader#34]
I got a report from a student saying that their code had been grading for a long time. This probably is related to (or the same case) as the jobs that @mwest1066 mentioned on Slack. We need to figure out what's going on here; I'll try to get grading job IDs from the DB for these jobs.

Relevant question: https://prairielearn.engr.illinois.edu/pl/course_instance/8240/instance_question/17397488/

**Comment by nwalters512** [comment]
Looks like this is a problem on the PL side. Relevant logs from when results are received for the above submission:

```
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: 2018-04-30T19:52:32.802Z - error: processGradingResult: error message=unsupported Unicode escape sequence, stack=Async Stacktrace:
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at async.series (/PrairieLearn/lib/assessment.js:357:17)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at sqldb.call (/PrairieLearn/lib/assessment.js:352:25)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:281:17
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:230:17)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: error: unsupported Unicode escape sequence
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at Connection.parseE (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:545:11)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at Connection.parseMessage (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:370:19)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at Socket.<anonymous> (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:113:22)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at emitOne (events.js:116:13)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at Socket.emit (events.js:211:7)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at addChunk (_stream_readable.js:263:12)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at readableAddChunk (_stream_readable.js:250:11)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at Socket.Readable.push (_stream_readable.js:208:10)
Apr 30 19:52:32 ip-10-0-0-204.us-east-2.compute.internal node[34472]: at TCP.onread (net.js:607:20), data={"sqlError":{"name":"error","length":206,"severity":"ERROR","code":"22P05","detail":"\\u0000 cannot be converted to text.","where":"JSON data, line 1: ...:{\"succeeded\":true,\"tests\":[{\"points\":0,\"output\":...","file":"json.c","line":"880","routine":"json_lex_string","message":"unsupported Unicode escape sequence"},"sql":"SELECT * FROM grading_jobs_process_external($1,$2,$3,$4,$5,$6)","sqlParams":[6949716,0,{"start_time":"2018-04-30T19:52:17.809Z","end_time":"2018-04-30T19:52:32.529Z","succeeded":true,"results":{"succeeded":true,"tests":[{"points":0,"output":"\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ntests is a Catch v1.9.1 host application.\nRun with -? for options\n\n-------------------------------------------------------------------------------\nFifty random tests of increasing complexity.\n-------------------------------------------------------------------------------\ntests.cpp:26\n...............................................................................\n\ntests.cpp:31: FAILED:\n  REQUIRE( beiju(nu) == s_beiju(nu) )\nwith expansion:\n  \"mlejuukwcibxubumenmeyatdrmydiajxloghiqotehz\u0000mndqtukwamzhlvihjouvsuyoypyulye-\n  im\"\n  ==\n  \"otehzmlejuukwcibxubumenmeyatdrmydiajxloghiqmndqtukwamzhlvihjouvsuyoypyulyei-\n  m\"\nwith message:\n  Input string was mndqtukwa[mlejuukwcibxubumenmeyatdrmydiajxloghiq]\n  mzhlvihjouvsuyoyp]yulyeim[otehz\n\n===============================================================================\ntest cases: 1 | 1 failed\nassertions: 5 | 4 passed | 1 failed\n\n","name":"Fifty random tests of increasing complexity.","max_points":1}],"score":0},"job_id":6949716,"received_time":"2018-04-30T19:52:15.686Z"},"2018-04-30T19:52:15.686Z","2018-04-30T19:52:17.809Z","2018-04-30T19:52:32.529Z"]}
```

**Comment by nwalters512** [comment]
Looks like this occurred because the result string contained a null byte. We could replace that with the literal "\u0000" in results?
