### ISSUE TITLE
Winston: "path" argument must be of type string

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieGrader#63]
```
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: info: Received job!
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: info: received 236901 from queue
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: options.stream will be removed in winston@4. Use winston.transports.Stream
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: internal/validators.js:125
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: ^
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at validateString (internal/validators.js:125:11)
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at Object.dirname (path.js:1260:5)
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at new File (/PrairieGrader/node_modules/winston/lib/winston/transports/file.js:69:27)
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at module.exports (/PrairieGrader/lib/jobLogger.js:21:9)
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at handleJob (/PrairieGrader/index.js:107:20)
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at receiveFromQueue (/PrairieGrader/index.js:80:19)
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at async.series (/PrairieGrader/lib/receiveFromQueue.js:107:13)
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at /PrairieGrader/node_modules/async/dist/async.js:3880:24
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at replenish (/PrairieGrader/node_modules/async/dist/async.js:1011:17)
Mar 18 16:23:29 ip-10-0-0-194.us-east-2.compute.internal node[4494]: at iterateeCallback (/PrairieGrader/node_modules/async/dist/async.js:995:17)
```

**Comment by mwest1066** [comment]
Already reported at https://github.com/Coggle/s3-streamlogger/issues/27
